### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by jackobenco016** [pnavaro/big-data#1]
Bonsoir,
Excusez-moi de vous déranger.
Est-ce possible de mettre les corrections sur Github ?

Cordialement

**Comment by pnavaro** [comment]
Elles y sont normalement, mais il en manque peut être. Ou ca exactement ?

**Comment by jackobenco016** [comment]
C'est par rapport aux notebooks sur les calculs parallèles.
Certains exercices ne me semblent pas corrigés.

Excusez-moi

**Comment by jackobenco016** [comment]
Notamment le TP6

**Comment by pnavaro** [comment]
Je pense que c'est bon, n'oubliez pas de fermer l'issue si c'est OK

commit: https://github.com/pnavaro/big-data/commit/3f58fa0af53d3ed858c1102565050e4ccf431dd7
